# Long Format Tables

In [121]:
# Import libraries
import numpy as np
import os
import json
import pandas as pd

In [122]:
# Data 2022
data2022 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP02.csv")
data2022.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)

In [123]:
# Data 2023
data2023 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP02.csv")
data2023.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,72751,NaN,5474,NaN,72751,NaN,-888888888,NaN,16880,NaN,...,NaN,2.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2023,acs1,group(DP02)
1,67483,NaN,5143,NaN,67483,NaN,-888888888,NaN,18886,NaN,...,NaN,2.4,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2023,acs1,group(DP02)
2,107857,NaN,6750,NaN,107857,NaN,-888888888,NaN,36888,NaN,...,NaN,1.7,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2023,acs1,group(DP02)
3,109586,NaN,6062,NaN,109586,NaN,-888888888,NaN,41600,NaN,...,NaN,1.0,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2023,acs1,group(DP02)
4,42309,NaN,4313,NaN,42309,NaN,-888888888,NaN,12298,NaN,...,NaN,3.3,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2023,acs1,group(DP02)

In [124]:
# Variable change log
change22to23 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2023-1yr-api-changes.csv")
change22to23.head()

,Product,Table ID,2023 Variable,2022 Variable,Change,2023 Label,2022 Label,Notes
0,Data Profile,DP02,DP02_0001E,DP02_0001E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Estimate!!HOUSEHOLDS BY TYPE!!Total households,NaN
1,Data Profile,DP02,DP02_0002E,DP02_0002E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
2,Data Profile,DP02,DP02_0003E,DP02_0003E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
3,Data Profile,DP02,DP02_0004E,DP02_0004E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
4,Data Profile,DP02,DP02_0005E,DP02_0005E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN

In [125]:
change22to23['Change'].value_counts()

Change
No Change           54016
No Match             1380
Variable Updated      314
Name: count, dtype: int64

In [126]:
# List with updated variables
change_list_22 = change22to23[change22to23['Change'] == 'Variable Updated']['2022 Variable'].tolist()

In [127]:
# List with variables in 2022
var_list_22 = data2022.columns.tolist()

In [128]:
# Look for variables in 2022 that have change in 2023
list(set(var_list_22) & set(change_list_22))

[]

In [129]:
# Since no variable has change, we can append both dataframes without further processing
# If changes were detected, we would need to change the name of the older df
all_data = pd.concat([data2022, data2023], ignore_index=True)
all_data.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)

In [130]:
# Get 2024 data
data2024 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP02.csv")
data2024.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,77199,NaN,5893,NaN,77199,NaN,-888888888,NaN,17291,NaN,...,NaN,2.5,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2024,acs1,group(DP02)
1,70182,NaN,5711,NaN,70182,NaN,-888888888,NaN,12520,NaN,...,NaN,2.3,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2024,acs1,group(DP02)
2,114790,NaN,6478,NaN,114790,NaN,-888888888,NaN,46084,NaN,...,NaN,1.5,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2024,acs1,group(DP02)
3,117332,NaN,6065,NaN,117332,NaN,-888888888,NaN,41134,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2024,acs1,group(DP02)
4,44279,NaN,3675,NaN,44279,NaN,-888888888,NaN,11736,NaN,...,NaN,3.3,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2024,acs1,group(DP02)

In [131]:
# Get variable change log
change23to24 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2024-1yr-api-changes.xlsx")
change23to24.head()

,Product,Table ID,2024 Variable,2023 Variable,Change,2024 Label,2023 Label,Notes
0,Data Profile,DP02,DP02_0001E,DP02_0001E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Estimate!!HOUSEHOLDS BY TYPE!!Total households,NaN
1,Data Profile,DP02,DP02_0002E,DP02_0002E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
2,Data Profile,DP02,DP02_0003E,DP02_0003E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
3,Data Profile,DP02,DP02_0004E,DP02_0004E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
4,Data Profile,DP02,DP02_0005E,DP02_0005E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN

In [132]:
# List with updated variables
change_list_23 = change23to24[change23to24['Change'] == 'Variable Updated']['2023 Variable'].tolist()

In [133]:
# List with variables in 2023
var_list_23 = data2023.columns.tolist()

In [134]:
# Look for variables in 2022 that have change in 2023
list(set(var_list_23) & set(change_list_23))

[]

In [135]:
# Since no variable has change, we can append both dataframes without further processing
# If changes were detected, we would need to change the name of the older df
all_data = pd.concat([all_data, data2024], ignore_index=True)
all_data.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)

In [136]:
# Clean dataframe
var_df = all_data.loc[:, ~all_data.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()                   # drop annotation columns
var_df = var_df.replace(-888888888, np.nan)
var_df = var_df.replace(-999999999, np.nan)
var_df

,DP02_0001E,DP02_0001M,DP02_0001PE,DP02_0001PM,DP02_0002E,DP02_0002M,DP02_0002PE,DP02_0002PM,DP02_0003E,DP02_0003M,...,DP02_0154M,DP02_0154PE,DP02_0154PM,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,4448,73474,NaN,15232,2442,20.7,3.4,4757,1483,...,4530,86.8,3.3,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,4580,67653,NaN,13438,2464,19.9,3.3,3164,1327,...,4683,93.4,3.1,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,6894,115928,NaN,42508,4207,36.7,3.6,17964,3380,...,6701,93.5,2.2,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,5481,114602,NaN,41410,3748,36.1,3.3,14542,2983,...,5690,95.8,1.4,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,3670,44758,NaN,9119,1576,20.4,3.8,2914,966,...,3621,85.0,4.5,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,64599,3384,64599,NaN,32036,3104,49.6,3.6,8281,1595,...,3507,96.1,1.5,795P200US3604413,NYC-Queens Community District 13--Queens Villa...,36,4413,2024,acs1,group(DP02)
161,50823,3291,50823,NaN,17534,2461,34.5,4.7,6352,1760,...,3129,92.5,3.0,795P200US3604414,NYC-Queens Community District 14--The Rockaway...,36,4414,2024,acs1,group(DP02)
162,65546,3411,65546,NaN,26486,2678,40.4,3.4,10166,1878,...,3569,93.9,1.8,795P200US3604501,NYC-Staten Island Community District 1--North ...,36,4501,2024,acs1,group(DP02)
163,47171,3115,47171,NaN,24988,2149,53.0,4.0,9635,1596,...,2899,90.7,2.9,795P200US3604502,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2024,acs1,group(DP02)
164,59552,3610,59552,NaN,33458,3057,56.2,4.2,13438,2080,...,3602,96.7,1.3,795P200US3604503,NYC-Staten Island Community District 3--South ...,36,4503,2024,acs1,group(DP02)

In [137]:
# labels
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2022.json", 'r') as f:
    data = json.load(f)

labels2022 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2023.json", 'r') as f:
    data = json.load(f)

labels2023 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

labels2024 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

In [138]:
# Keep only DP02
labels2022 = labels2022[labels2022['group'] == 'DP02'].copy()
labels2023 = labels2023[labels2023['group'] == 'DP02'].copy()
labels2024 = labels2024[labels2024['group'] == 'DP02'].copy()
labels2022

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN
10,DP02_0125E,Estimate!!ANCESTRY!!Total population!!American,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0125EA,DP02_0125M,DP02_0125MA",NaN
11,DP02_0054PE,Percent!!SCHOOL ENROLLMENT!!Population 3 years...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0054PEA,DP02_0054PM,DP02_0054PMA",NaN
15,DP02_0124E,Estimate!!ANCESTRY!!Total population,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0124EA,DP02_0124M,DP02_0124MA",NaN
17,DP02_0123E,Estimate!!LANGUAGE SPOKEN AT HOME!!Population ...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0123EA,DP02_0123M,DP02_0123MA",NaN
...,...,...,...,...,...,...,...,...,...,...
1365,DP02_0112PE,Percent!!LANGUAGE SPOKEN AT HOME!!Population 5...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0112PEA,DP02_0112PM,DP02_0112PMA",NaN
1369,DP02_0049PE,Percent!!GRANDPARENTS!!Number of grandparents ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0049PEA,DP02_0049PM,DP02_0049PMA",NaN
1379,DP02_0099E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0099EA,DP02_0099M,DP02_0099MA",NaN
1383,DP02_0098E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0098EA,DP02_0098M,DP02_0098MA",NaN
1385,DP02_0036PE,Percent!!MARITAL STATUS!!Females 15 years and ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0036PEA,DP02_0036PM,DP02_0036PMA",NaN

In [139]:
# Look for variables in 2023 not in 2022 (or the other way around)
list(set(labels2023['variable'].tolist()) - set(labels2022['variable'].tolist()))

[]

In [140]:
# Look for variables in 2024 not in 2023 (or the other way around)
list(set(labels2024['variable'].tolist()) - set(labels2023['variable'].tolist()))

[]

In [141]:
labels2024.head()

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN
10,DP02_0125E,Estimate!!ANCESTRY!!Total population!!American,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0125EA,DP02_0125M,DP02_0125MA",NaN
11,DP02_0054PE,Percent!!SCHOOL ENROLLMENT!!Population 3 years...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0054PEA,DP02_0054PM,DP02_0054PMA",NaN
15,DP02_0124E,Estimate!!ANCESTRY!!Total population,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0124EA,DP02_0124M,DP02_0124MA",NaN
17,DP02_0123E,Estimate!!LANGUAGE SPOKEN AT HOME!!Population ...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0123EA,DP02_0123M,DP02_0123MA",NaN

In [142]:
meta_labels_df = labels2024[['variable', 'label', 'group']]
meta_labels_df = meta_labels_df.rename(columns = {'variable' : 'var_name'})                                     # Change column names
meta_labels_df['var_type'] = meta_labels_df['var_name'].str.extract(r'\d+([A-Z]+)', expand=False)               # Gen var type
meta_labels_df['var_type'] = meta_labels_df['var_type'].replace({'E': 'Estimate','PE': 'Percentage'})           # Change type description
meta_labels_df['var_label'] = meta_labels_df['label'].replace('Estimate|Percent', '', regex=True)               # Gen base label
meta_labels_df = meta_labels_df.drop_duplicates()                                                               # Drop possible duplicates
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.lstrip('!!')                                      # Remove initial '!!'
meta_labels_df['var_topic'] = meta_labels_df['var_label'].str.split('!!').str[0]                                # Add var topic
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.replace('!!', ' - ', regex=True)                  # Remove other '!!'
meta_labels_df['var_attributes'] = meta_labels_df['var_name'].str[:-1] + 'M (marging of error)'                 # Gen column with var attributes
meta_labels_df = meta_labels_df[['var_name', 'var_type', 'var_topic', 'var_label', 'var_attributes', 'group']]
meta_labels_df

,var_name,var_type,var_topic,var_label,var_attributes,group
3,DP02_0126E,Estimate,ANCESTRY,ANCESTRY - Total population - Arab,DP02_0126M (marging of error),DP02
10,DP02_0125E,Estimate,ANCESTRY,ANCESTRY - Total population - American,DP02_0125M (marging of error),DP02
11,DP02_0054PE,Percentage,SCHOOL ENROLLMENT,SCHOOL ENROLLMENT - Population 3 years and ove...,DP02_0054PM (marging of error),DP02
15,DP02_0124E,Estimate,ANCESTRY,ANCESTRY - Total population,DP02_0124M (marging of error),DP02
17,DP02_0123E,Estimate,LANGUAGE SPOKEN AT HOME,LANGUAGE SPOKEN AT HOME - Population 5 years a...,DP02_0123M (marging of error),DP02
...,...,...,...,...,...,...
1394,DP02_0112PE,Percentage,LANGUAGE SPOKEN AT HOME,LANGUAGE SPOKEN AT HOME - Population 5 years a...,DP02_0112PM (marging of error),DP02
1398,DP02_0049PE,Percentage,GRANDPARENTS,GRANDPARENTS - Number of grandparents living w...,DP02_0049PM (marging of error),DP02
1409,DP02_0099E,Estimate,YEAR OF ENTRY,YEAR OF ENTRY - Population born outside the Un...,DP02_0099M (marging of error),DP02
1413,DP02_0098E,Estimate,YEAR OF ENTRY,YEAR OF ENTRY - Population born outside the Un...,DP02_0098M (marging of error),DP02
1415,DP02_0036PE,Percentage,MARITAL STATUS,MARITAL STATUS - Females 15 years and over - D...,DP02_0036PM (marging of error),DP02

In [143]:
# Save data
data_sample = 'acs1'
data_geography = 'PUMA'
data_group = 'DP02'
group_desc = 'SOCIAL_CHAR'


directory = fr'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\{data_sample}\panel\{data_geography}'
file_name = f'{data_sample}_paneL_2024_{data_geography}_NYC_{data_group}_{group_desc}.xlsx'

# Ensure the folder exists (create if missing)
os.makedirs(directory, exist_ok=True)


full_path = os.path.join(directory, file_name)

with pd.ExcelWriter(full_path) as writer:
    var_df.to_excel(writer, sheet_name = 'data', index = False)
    meta_labels_df.to_excel(writer, sheet_name = 'geo_labels', index = False)