# Long Format Tables

In [1]:
# Import libraries
import numpy as np
import os
import json
import pandas as pd

## DP02

In [ ]:
# Get the Data
data2022 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP02.csv")
data2023 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP02.csv")
data2024 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP02.csv")
data2022.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)

In [ ]:
# Variable change log
change22to23 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2023-1yr-api-changes.csv")
change23to24 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2024-1yr-api-changes.xlsx")
change22to23.head()

,Product,Table ID,2023 Variable,2022 Variable,Change,2023 Label,2022 Label,Notes
0,Data Profile,DP02,DP02_0001E,DP02_0001E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Estimate!!HOUSEHOLDS BY TYPE!!Total households,NaN
1,Data Profile,DP02,DP02_0002E,DP02_0002E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
2,Data Profile,DP02,DP02_0003E,DP02_0003E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
3,Data Profile,DP02,DP02_0004E,DP02_0004E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN
4,Data Profile,DP02,DP02_0005E,DP02_0005E,No Change,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,NaN

In [ ]:
# labels
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2022.json", 'r') as f:
    data = json.load(f)

labels2022 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2023.json", 'r') as f:
    data = json.load(f)

labels2023 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

labels2024 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

### Data

In [6]:
# Look for variable changes between 2022 and 2023
# List with updated variables
change_list_22 = change22to23[change22to23['Change'] == 'Variable Updated']['2022 Variable'].tolist()
# List with variables in 2022
var_list_22 = data2022.columns.tolist()
# Look for variables in 2022 that have change in 2023
list(set(var_list_22) & set(change_list_22))

[]

In [7]:
# Since no variable has change, we can append both dataframes without further processing
# If changes were detected, we would need to change the name of the older df
all_data = pd.concat([data2022, data2023], ignore_index=True)
all_data.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)

In [ ]:
# Look for variable changes from 2022 to 2023
# List with updated variables
change_list_23 = change23to24[change23to24['Change'] == 'Variable Updated']['2023 Variable'].tolist()
# List with variables in 2023
var_list_23 = data2023.columns.tolist()
# Compare lists
list(set(var_list_23) & set(change_list_23))

[]

In [11]:
# Since no variable has change, we can append both dataframes without further processing
# If changes were detected, we would need to change the name of the older df
all_data = pd.concat([all_data, data2023], ignore_index=True)
all_data.head()

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)

In [12]:
# Clean dataframe
var_df = all_data.loc[:, ~all_data.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()                   # drop annotation columns
var_df = var_df.replace(-888888888, np.nan)
var_df = var_df.replace(-999999999, np.nan)
var_df

,DP02_0001E,DP02_0001M,DP02_0001PE,DP02_0001PM,DP02_0002E,DP02_0002M,DP02_0002PE,DP02_0002PM,DP02_0003E,DP02_0003M,...,DP02_0154M,DP02_0154PE,DP02_0154PM,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,4448,73474,NaN,15232,2442,20.7,3.4,4757,1483,...,4530,86.8,3.3,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,4580,67653,NaN,13438,2464,19.9,3.3,3164,1327,...,4683,93.4,3.1,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,6894,115928,NaN,42508,4207,36.7,3.6,17964,3380,...,6701,93.5,2.2,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,5481,114602,NaN,41410,3748,36.1,3.3,14542,2983,...,5690,95.8,1.4,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,3670,44758,NaN,9119,1576,20.4,3.8,2914,966,...,3621,85.0,4.5,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,66010,3517,66010,NaN,31593,2799,47.9,3.4,9821,1689,...,3563,94.2,1.8,795P200US3604413,NYC-Queens Community District 13--Queens Villa...,36,4413,2023,acs1,group(DP02)
161,45165,3747,45165,NaN,14174,2080,31.4,4.4,5740,1389,...,3779,89.4,3.5,795P200US3604414,NYC-Queens Community District 14--The Rockaway...,36,4414,2023,acs1,group(DP02)
162,60605,2839,60605,NaN,23667,2377,39.1,3.7,9424,1678,...,3078,86.2,2.7,795P200US3604501,NYC-Staten Island Community District 1--North ...,36,4501,2023,acs1,group(DP02)
163,47423,2954,47423,NaN,24169,2525,51.0,4.4,9318,1513,...,2760,91.2,2.4,795P200US3604502,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2023,acs1,group(DP02)
164,61498,3263,61498,NaN,37218,2701,60.5,3.8,17046,2179,...,3322,94.7,2.0,795P200US3604503,NYC-Staten Island Community District 3--South ...,36,4503,2023,acs1,group(DP02)

### Labels

In [14]:
# Keep only DP02
labels2022 = labels2022[labels2022['group'] == 'DP02'].copy()
labels2023 = labels2023[labels2023['group'] == 'DP02'].copy()
labels2024 = labels2024[labels2024['group'] == 'DP02'].copy()
labels2022

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN
10,DP02_0125E,Estimate!!ANCESTRY!!Total population!!American,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0125EA,DP02_0125M,DP02_0125MA",NaN
11,DP02_0054PE,Percent!!SCHOOL ENROLLMENT!!Population 3 years...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0054PEA,DP02_0054PM,DP02_0054PMA",NaN
15,DP02_0124E,Estimate!!ANCESTRY!!Total population,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0124EA,DP02_0124M,DP02_0124MA",NaN
17,DP02_0123E,Estimate!!LANGUAGE SPOKEN AT HOME!!Population ...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0123EA,DP02_0123M,DP02_0123MA",NaN
...,...,...,...,...,...,...,...,...,...,...
1365,DP02_0112PE,Percent!!LANGUAGE SPOKEN AT HOME!!Population 5...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0112PEA,DP02_0112PM,DP02_0112PMA",NaN
1369,DP02_0049PE,Percent!!GRANDPARENTS!!Number of grandparents ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0049PEA,DP02_0049PM,DP02_0049PMA",NaN
1379,DP02_0099E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0099EA,DP02_0099M,DP02_0099MA",NaN
1383,DP02_0098E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0098EA,DP02_0098M,DP02_0098MA",NaN
1385,DP02_0036PE,Percent!!MARITAL STATUS!!Females 15 years and ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0036PEA,DP02_0036PM,DP02_0036PMA",NaN

In [15]:
# Look for variables in 2023 not in 2022 (or the other way around)
list(set(labels2023['variable'].tolist()) - set(labels2022['variable'].tolist()))

[]

In [16]:
# Look for variables in 2024 not in 2023 (or the other way around)
list(set(labels2024['variable'].tolist()) - set(labels2023['variable'].tolist()))

[]

In [ ]:
# Format labels
meta_labels_df = labels2024[['variable', 'label', 'group']]
meta_labels_df = meta_labels_df.rename(columns = {'variable' : 'var_name'})                                     # Change column names
meta_labels_df['var_type'] = meta_labels_df['var_name'].str.extract(r'\d+([A-Z]+)', expand=False)               # Gen var type
meta_labels_df['var_type'] = meta_labels_df['var_type'].replace({'E': 'Estimate','PE': 'Percentage'})           # Change type description
meta_labels_df['var_label'] = meta_labels_df['label'].replace('Estimate|Percent', '', regex=True)               # Gen base label
meta_labels_df = meta_labels_df.drop_duplicates()                                                               # Drop possible duplicates
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.lstrip('!!')                                      # Remove initial '!!'
meta_labels_df['var_topic'] = meta_labels_df['var_label'].str.split('!!').str[0]                                # Add var topic
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.replace('!!', ' - ', regex=True)                  # Remove other '!!'
meta_labels_df['var_attributes'] = meta_labels_df['var_name'].str[:-1] + 'M (marging of error)'                 # Gen column with var attributes
meta_labels_df = meta_labels_df[['var_name', 'var_type', 'var_topic', 'var_label', 'var_attributes', 'group']]  # Re-order columns
meta_labels_df = meta_labels_df.sort_values(by = 'var_name')                                                    # Sort values by var_name
meta_labels_df

,var_name,var_type,var_topic,var_label,var_attributes,group
1250,DP02_0001E,Estimate,HOUSEHOLDS BY TYPE,HOUSEHOLDS BY TYPE - Total households,DP02_0001M (marging of error),DP02
688,DP02_0001PE,Percentage,HOUSEHOLDS BY TYPE,HOUSEHOLDS BY TYPE - Total households,DP02_0001PM (marging of error),DP02
1242,DP02_0002E,Estimate,HOUSEHOLDS BY TYPE,HOUSEHOLDS BY TYPE - Total households - Marrie...,DP02_0002M (marging of error),DP02
894,DP02_0002PE,Percentage,HOUSEHOLDS BY TYPE,HOUSEHOLDS BY TYPE - Total households - Marrie...,DP02_0002PM (marging of error),DP02
1234,DP02_0003E,Estimate,HOUSEHOLDS BY TYPE,HOUSEHOLDS BY TYPE - Total households - Marrie...,DP02_0003M (marging of error),DP02
...,...,...,...,...,...,...
740,DP02_0152PE,Percentage,COMPUTERS AND INTERNET USE,COMPUTERS AND INTERNET USE - Total households,DP02_0152PM (marging of error),DP02
1189,DP02_0153E,Estimate,COMPUTERS AND INTERNET USE,COMPUTERS AND INTERNET USE - Total households ...,DP02_0153M (marging of error),DP02
931,DP02_0153PE,Percentage,COMPUTERS AND INTERNET USE,COMPUTERS AND INTERNET USE - Total households ...,DP02_0153PM (marging of error),DP02
1184,DP02_0154E,Estimate,COMPUTERS AND INTERNET USE,COMPUTERS AND INTERNET USE - Total households ...,DP02_0154M (marging of error),DP02
1079,DP02_0154PE,Percentage,COMPUTERS AND INTERNET USE,COMPUTERS AND INTERNET USE - Total households ...,DP02_0154PM (marging of error),DP02

### Save data

In [19]:
# Save data
data_sample = 'acs1'
data_geography = 'PUMA'
data_group = 'DP02'
group_desc = 'SOCIAL_CHAR'


directory = fr'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\{data_sample}\panel\{data_geography}'
file_name = f'{data_sample}_paneL_2024_{data_geography}_NYC_{data_group}_{group_desc}.xlsx'

# Ensure the folder exists (create if missing)
os.makedirs(directory, exist_ok=True)


full_path = os.path.join(directory, file_name)

with pd.ExcelWriter(full_path) as writer:
    var_df.to_excel(writer, sheet_name = 'data', index = False)
    meta_labels_df.to_excel(writer, sheet_name = 'var_labels', index = False)

## DP03

In [20]:
# Data
data2022 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP03.csv")
data2023 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP03.csv")
data2024 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP03.csv")

In [21]:
# Variable change files
change22to23 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2023-1yr-api-changes.csv")
change23to24 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2024-1yr-api-changes.xlsx")

In [22]:
# Variable labels files
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2022.json", 'r') as f:
    data = json.load(f)

labels2022 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2023.json", 'r') as f:
    data = json.load(f)

labels2023 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

labels2024 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

### Data

In [23]:
# Look for variable changes between 2022 and 2023
# List with updated variables
change_list_22 = change22to23[change22to23['Change'] == 'Variable Updated']['2022 Variable'].tolist()
# List with variables in 2022
var_list_22 = data2022.columns.tolist()
# Look for variables in 2022 that have change in 2023
list(set(var_list_22) & set(change_list_22))

[]

In [24]:
# If no variable has been updated, a simple concat is enough
# Check condition
assert list(set(var_list_22) & set(change_list_22)) == []
# Concat dataframes
all_data = pd.concat([data2022, data2023], ignore_index=True)

In [25]:
# Look for variable changes between 2023 and 2024
# List with updated variables
change_list_23 = change23to24[change23to24['Change'] == 'Variable Updated']['2023 Variable'].tolist()
# List with variables in 2023
var_list_23 = data2023.columns.tolist()
# Look for variables in 2022 that have change in 2023
list(set(var_list_23) & set(change_list_23))

[]

In [26]:
# If no variable has been updated, a simple concat is enough
# Check condition
assert list(set(var_list_23) & set(change_list_23)) == []
# Concat dataframes
all_data = pd.concat([all_data, data2024], ignore_index=True)

In [27]:
# Basic dataframe cleaning
var_df = all_data.loc[:, ~all_data.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()                   # drop annotation columns
var_df = var_df.replace(-888888888, np.nan)                                                            # recode missing values
var_df = var_df.replace(-999999999, np.nan)                                                            # recode missing values
var_df

,DP03_0001E,DP03_0001M,DP03_0001PE,DP03_0001PM,DP03_0002E,DP03_0002M,DP03_0002PE,DP03_0002PM,DP03_0003E,DP03_0003M,...,DP03_0137M,DP03_0137PE,DP03_0137PM,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,129274,7944,129274,NaN,75542,5366,58.4,2.8,75482,5343,...,NaN,28.3,4.1,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP03)
1,105613,8182,105613,NaN,76774,6544,72.7,3.7,76774,6544,...,NaN,18.4,4.0,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP03)
2,196290,11200,196290,NaN,129334,9669,65.9,2.5,128942,9549,...,NaN,21.2,3.6,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP03)
3,180942,8483,180942,NaN,128201,7048,70.9,2.2,128201,7048,...,NaN,11.2,2.3,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP03)
4,95588,8122,95588,NaN,60689,7281,63.5,4.2,60689,7281,...,NaN,33.1,5.6,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP03)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,165536,8726,165536,NaN,103018,6715,62.2,2.2,103018,6715,...,NaN,24.0,4.1,795P200US3604413,NYC-Queens Community District 13--Queens Villa...,36,4413,2024,acs1,group(DP03)
161,104770,8237,104770,NaN,59117,7277,56.4,3.7,58673,7214,...,NaN,37.6,6.5,795P200US3604414,NYC-Queens Community District 14--The Rockaway...,36,4414,2024,acs1,group(DP03)
162,152902,7711,152902,NaN,91362,6084,59.8,2.5,91319,6074,...,NaN,32.3,5.1,795P200US3604501,NYC-Staten Island Community District 1--North ...,36,4501,2024,acs1,group(DP03)
163,115611,7868,115611,NaN,68769,6099,59.5,2.8,68615,6091,...,NaN,28.6,7.1,795P200US3604502,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2024,acs1,group(DP03)
164,138293,9496,138293,NaN,88797,7014,64.2,2.3,88797,7014,...,NaN,19.0,6.4,795P200US3604503,NYC-Staten Island Community District 3--South ...,36,4503,2024,acs1,group(DP03)

### Labels

In [28]:
# Keep only DP03
labels2022 = labels2022[labels2022['group'] == 'DP03'].copy()
labels2023 = labels2023[labels2023['group'] == 'DP03'].copy()
labels2024 = labels2024[labels2024['group'] == 'DP03'].copy()
labels2022

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
13,DP03_0048PE,Percent!!CLASS OF WORKER!!Civilian employed po...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0048PEA,DP03_0048PM,DP03_0048PMA",NaN
21,DP03_0022PE,Percent!!COMMUTING TO WORK!!Workers 16 years a...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0022PEA,DP03_0022PM,DP03_0022PMA",NaN
31,DP03_0111PE,Percent!!HEALTH INSURANCE COVERAGE!!Civilian n...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0111PEA,DP03_0111PM,DP03_0111PMA",NaN
35,DP03_0109E,Estimate!!HEALTH INSURANCE COVERAGE!!Civilian ...,Selected Economic Characteristics,int,DP03,0,NaN,NaN,"DP03_0109EA,DP03_0109M,DP03_0109MA",NaN
40,DP03_0035PE,Percent!!INDUSTRY!!Civilian employed populatio...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0035PEA,DP03_0035PM,DP03_0035PMA",NaN
...,...,...,...,...,...,...,...,...,...,...
1364,DP03_0050E,Estimate!!CLASS OF WORKER!!Civilian employed p...,Selected Economic Characteristics,int,DP03,0,NaN,NaN,"DP03_0050EA,DP03_0050M,DP03_0050MA",NaN
1366,DP03_0026PE,Percent!!OCCUPATION!!Civilian employed populat...,Selected Economic Characteristics,int,DP03,0,NaN,NaN,"DP03_0026PEA,DP03_0026PM,DP03_0026PMA",NaN
1372,DP03_0051E,Estimate!!INCOME AND BENEFITS (IN 2022 INFLATI...,Selected Economic Characteristics,int,DP03,0,NaN,NaN,"DP03_0051EA,DP03_0051M,DP03_0051MA",NaN
1377,DP03_0115PE,Percent!!HEALTH INSURANCE COVERAGE!!Civilian n...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0115PEA,DP03_0115PM,DP03_0115PMA",NaN
1382,DP03_0039PE,Percent!!INDUSTRY!!Civilian employed populatio...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0039PEA,DP03_0039PM,DP03_0039PMA",NaN

In [29]:
# Look for variables in 2023 not in 2022 (or the other way around)
list(set(labels2023['variable'].tolist()) - set(labels2022['variable'].tolist()))

[]

In [30]:
# Look for variables in 2024 not in 2023 (or the other way around)
list(set(labels2024['variable'].tolist()) - set(labels2023['variable'].tolist()))

[]

In [31]:
# If label list match, I can use any
assert list(set(labels2023['variable'].tolist()) - set(labels2022['variable'].tolist())) == []
assert list(set(labels2024['variable'].tolist()) - set(labels2023['variable'].tolist())) == []

# Format variable labels
meta_labels_df = labels2024[['variable', 'label', 'group']]                                                     # Select only necessary columns
meta_labels_df = meta_labels_df.rename(columns = {'variable' : 'var_name'})                                     # Change column names
meta_labels_df['var_type'] = meta_labels_df['var_name'].str.extract(r'\d+([A-Z]+)', expand=False)               # Gen var type
meta_labels_df['var_type'] = meta_labels_df['var_type'].replace({'E': 'Estimate','PE': 'Percentage'})           # Change type description
meta_labels_df['var_label'] = meta_labels_df['label'].replace('Estimate|Percent', '', regex=True)               # Gen base label
meta_labels_df = meta_labels_df.drop_duplicates()                                                               # Drop possible duplicates
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.lstrip('!!')                                      # Remove initial '!!'
meta_labels_df['var_topic'] = meta_labels_df['var_label'].str.split('!!').str[0]                                # Add var topic
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.replace('!!', ' - ', regex=True)                  # Remove other '!!'
meta_labels_df['var_attributes'] = meta_labels_df['var_name'].str[:-1] + 'M (marging of error)'                 # Gen column with var attributes
meta_labels_df = meta_labels_df[['var_name', 'var_type', 'var_topic', 'var_label', 'var_attributes', 'group']]  # Re-order columns
meta_labels_df = meta_labels_df.sort_values(by = 'var_name')                                                    # Sort values by var_name
meta_labels_df

,var_name,var_type,var_topic,var_label,var_attributes,group
474,DP03_0001E,Estimate,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and over,DP03_0001M (marging of error),DP03
904,DP03_0001PE,Percentage,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and over,DP03_0001PM (marging of error),DP03
453,DP03_0002E,Estimate,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and ov...,DP03_0002M (marging of error),DP03
373,DP03_0002PE,Percentage,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and ov...,DP03_0002PM (marging of error),DP03
459,DP03_0003E,Estimate,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and ov...,DP03_0003M (marging of error),DP03
...,...,...,...,...,...,...
385,DP03_0135PE,Percentage,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03_0135PM (marging of error),DP03
460,DP03_0136E,Estimate,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03_0136M (marging of error),DP03
515,DP03_0136PE,Percentage,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03_0136PM (marging of error),DP03
634,DP03_0137E,Estimate,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03_0137M (marging of error),DP03
686,DP03_0137PE,Percentage,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03_0137PM (marging of error),DP03

### Save Data

In [32]:
# Save data
data_sample = 'acs1'
data_geography = 'PUMA'
data_group = 'DP03'
group_desc = 'ECONOMIC_CHAR'


directory = fr'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\{data_sample}\panel\{data_geography}'
file_name = f'{data_sample}_paneL_2024_{data_geography}_NYC_{data_group}_{group_desc}.xlsx'

# Ensure the folder exists (create if missing)
os.makedirs(directory, exist_ok=True)


full_path = os.path.join(directory, file_name)

with pd.ExcelWriter(full_path) as writer:
    var_df.to_excel(writer, sheet_name = 'data', index = False)
    meta_labels_df.to_excel(writer, sheet_name = 'var_labels', index = False)

## DP04

In [33]:
# Data
data2022 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP04.csv")
data2023 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP04.csv")
data2024 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP04.csv")

In [34]:
# Variable change files
change22to23 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2023-1yr-api-changes.csv")
change23to24 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2024-1yr-api-changes.xlsx")

In [35]:
# Variable labels files
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2022.json", 'r') as f:
    data = json.load(f)

labels2022 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2023.json", 'r') as f:
    data = json.load(f)

labels2023 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

labels2024 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

### Data

In [36]:
# Look for variable changes between 2022 and 2023
# List with updated variables
change_list_22 = change22to23[change22to23['Change'] == 'Variable Updated']['2022 Variable'].tolist()
# List with variables in 2022
var_list_22 = data2022.columns.tolist()
# Look for variables in 2022 that have change in 2023
list(set(var_list_22) & set(change_list_22))

[]

In [37]:
# If no variable has been updated, a simple concat is enough
# Check condition
assert list(set(var_list_22) & set(change_list_22)) == []
# Concat dataframes
all_data = pd.concat([data2022, data2023], ignore_index=True)

In [38]:
# Look for variable changes between 2023 and 2024
# List with updated variables
change_list_23 = change23to24[change23to24['Change'] == 'Variable Updated']['2023 Variable'].tolist()
# List with variables in 2023
var_list_23 = data2023.columns.tolist()
# Look for variables in 2022 that have change in 2023
list(set(var_list_23) & set(change_list_23))

[]

In [39]:
# If no variable has been updated, a simple concat is enough
# Check condition
assert list(set(var_list_23) & set(change_list_23)) == []
# Concat dataframes
all_data = pd.concat([all_data, data2024], ignore_index=True)

In [40]:
# Basic dataframe cleaning
var_df = all_data.loc[:, ~all_data.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()                   # drop annotation columns
var_df = var_df.replace(-888888888, np.nan)                                                            # recode missing values
var_df = var_df.replace(-999999999, np.nan)                                                            # recode missing values
var_df

,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,DP04_0003E,DP04_0003M,...,DP04_0143M,DP04_0143PE,DP04_0143PM,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,81731,4408,81731,NaN,73474,4448,89.9,2.9,8257,2424,...,1056,NaN,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP04)
1,80316,5107,80316,NaN,67653,4580,84.2,3.7,12663,3228,...,630,NaN,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP04)
2,131382,7329,131382,NaN,115928,6894,88.2,2.2,15454,3085,...,1809,NaN,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP04)
3,139718,7115,139718,NaN,114602,5481,82.0,3.1,25116,5085,...,867,NaN,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP04)
4,48621,3777,48621,NaN,44758,3670,92.1,2.4,3863,1203,...,1542,NaN,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP04)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,67166,3437,67166,NaN,64599,3384,96.2,1.3,2567,868,...,428,NaN,NaN,795P200US3604413,NYC-Queens Community District 13--Queens Villa...,36,4413,2024,acs1,group(DP04)
161,52171,3396,52171,NaN,50823,3291,97.4,1.4,1348,763,...,1066,NaN,NaN,795P200US3604414,NYC-Queens Community District 14--The Rockaway...,36,4414,2024,acs1,group(DP04)
162,71293,3334,71293,NaN,65546,3411,91.9,2.2,5747,1601,...,922,NaN,NaN,795P200US3604501,NYC-Staten Island Community District 1--North ...,36,4501,2024,acs1,group(DP04)
163,51174,2981,51174,NaN,47171,3115,92.2,2.4,4003,1215,...,787,NaN,NaN,795P200US3604502,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2024,acs1,group(DP04)
164,63381,3659,63381,NaN,59552,3610,94.0,2.2,3829,1462,...,236,NaN,NaN,795P200US3604503,NYC-Staten Island Community District 3--South ...,36,4503,2024,acs1,group(DP04)

### Labels

In [41]:
# Keep only DP04
labels2022 = labels2022[labels2022['group'] == 'DP04'].copy()
labels2023 = labels2023[labels2023['group'] == 'DP04'].copy()
labels2024 = labels2024[labels2024['group'] == 'DP04'].copy()
labels2022

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
5,DP04_0047E,Estimate!!HOUSING TENURE!!Occupied housing uni...,Selected Housing Characteristics,int,DP04,0,NaN,NaN,"DP04_0047EA,DP04_0047M,DP04_0047MA",NaN
8,DP04_0046E,Estimate!!HOUSING TENURE!!Occupied housing uni...,Selected Housing Characteristics,int,DP04,0,NaN,NaN,"DP04_0046EA,DP04_0046M,DP04_0046MA",NaN
9,DP04_0016PE,Percent!!YEAR STRUCTURE BUILT!!Total housing u...,Selected Housing Characteristics,int,DP04,0,NaN,NaN,"DP04_0016PEA,DP04_0016PM,DP04_0016PMA",NaN
12,DP04_0049E,Estimate!!HOUSING TENURE!!Occupied housing uni...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0049EA,DP04_0049M,DP04_0049MA",NaN
14,DP04_0029PE,Percent!!ROOMS!!Total housing units!!2 rooms,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0029PEA,DP04_0029PM,DP04_0029PMA",NaN
...,...,...,...,...,...,...,...,...,...,...
1371,DP04_0082PE,"Percent!!VALUE!!Owner-occupied units!!$50,000 ...",Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0082PEA,DP04_0082PM,DP04_0082PMA",NaN
1373,DP04_0105PE,Percent!!SELECTED MONTHLY OWNER COSTS (SMOC)!!...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0105PEA,DP04_0105PM,DP04_0105PMA",NaN
1374,DP04_0097E,Estimate!!SELECTED MONTHLY OWNER COSTS (SMOC)!...,Selected Housing Characteristics,int,DP04,0,NaN,NaN,"DP04_0097EA,DP04_0097M,DP04_0097MA",NaN
1380,DP04_0096E,Estimate!!SELECTED MONTHLY OWNER COSTS (SMOC)!...,Selected Housing Characteristics,int,DP04,0,NaN,NaN,"DP04_0096EA,DP04_0096M,DP04_0096MA",NaN
1384,DP04_0095PE,Percent!!SELECTED MONTHLY OWNER COSTS (SMOC)!!...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0095PEA,DP04_0095PM,DP04_0095PMA",NaN

In [42]:
# Look for variables in 2023 not in 2022 (or the other way around)
list(set(labels2023['variable'].tolist()) - set(labels2022['variable'].tolist()))

[]

In [43]:
# Look for variables in 2024 not in 2023 (or the other way around)
list(set(labels2024['variable'].tolist()) - set(labels2023['variable'].tolist()))

[]

In [44]:
# If label list match, I can use any
assert list(set(labels2023['variable'].tolist()) - set(labels2022['variable'].tolist())) == []
assert list(set(labels2024['variable'].tolist()) - set(labels2023['variable'].tolist())) == []

# Format variable labels
meta_labels_df = labels2024[['variable', 'label', 'group']]                                                     # Select only necessary columns
meta_labels_df = meta_labels_df.rename(columns = {'variable' : 'var_name'})                                     # Change column names
meta_labels_df['var_type'] = meta_labels_df['var_name'].str.extract(r'\d+([A-Z]+)', expand=False)               # Gen var type
meta_labels_df['var_type'] = meta_labels_df['var_type'].replace({'E': 'Estimate','PE': 'Percentage'})           # Change type description
meta_labels_df['var_label'] = meta_labels_df['label'].replace('Estimate|Percent', '', regex=True)               # Gen base label
meta_labels_df = meta_labels_df.drop_duplicates()                                                               # Drop possible duplicates
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.lstrip('!!')                                      # Remove initial '!!'
meta_labels_df['var_topic'] = meta_labels_df['var_label'].str.split('!!').str[0]                                # Add var topic
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.replace('!!', ' - ', regex=True)                  # Remove other '!!'
meta_labels_df['var_attributes'] = meta_labels_df['var_name'].str[:-1] + 'M (marging of error)'                 # Gen column with var attributes
meta_labels_df = meta_labels_df[['var_name', 'var_type', 'var_topic', 'var_label', 'var_attributes', 'group']]  # Re-order columns
meta_labels_df = meta_labels_df.sort_values(by = 'var_name')                                                    # Sort values by var_name
meta_labels_df

,var_name,var_type,var_topic,var_label,var_attributes,group
752,DP04_0001E,Estimate,HOUSING OCCUPANCY,HOUSING OCCUPANCY - Total housing units,DP04_0001M (marging of error),DP04
1107,DP04_0001PE,Percentage,HOUSING OCCUPANCY,HOUSING OCCUPANCY - Total housing units,DP04_0001PM (marging of error),DP04
795,DP04_0002E,Estimate,HOUSING OCCUPANCY,HOUSING OCCUPANCY - Total housing units - Occu...,DP04_0002M (marging of error),DP04
1288,DP04_0002PE,Percentage,HOUSING OCCUPANCY,HOUSING OCCUPANCY - Total housing units - Occu...,DP04_0002PM (marging of error),DP04
791,DP04_0003E,Estimate,HOUSING OCCUPANCY,HOUSING OCCUPANCY - Total housing units - Vaca...,DP04_0003M (marging of error),DP04
...,...,...,...,...,...,...
93,DP04_0141PE,Percentage,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,DP04_0141PM (marging of error),DP04
1256,DP04_0142E,Estimate,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,DP04_0142M (marging of error),DP04
284,DP04_0142PE,Percentage,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,DP04_0142PM (marging of error),DP04
1224,DP04_0143E,Estimate,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,DP04_0143M (marging of error),DP04
436,DP04_0143PE,Percentage,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME...,DP04_0143PM (marging of error),DP04

### Save Data

In [45]:
# Save data
data_sample = 'acs1'
data_geography = 'PUMA'
data_group = 'DP04'
group_desc = 'HOUSING_CHAR'


directory = fr'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\{data_sample}\panel\{data_geography}'
file_name = f'{data_sample}_paneL_2024_{data_geography}_NYC_{data_group}_{group_desc}.xlsx'

# Ensure the folder exists (create if missing)
os.makedirs(directory, exist_ok=True)


full_path = os.path.join(directory, file_name)

with pd.ExcelWriter(full_path) as writer:
    var_df.to_excel(writer, sheet_name = 'data', index = False)
    meta_labels_df.to_excel(writer, sheet_name = 'var_labels', index = False)

## DP05

In [46]:
# Data
data2022 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP05.csv")
data2023 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP05.csv")
data2024 = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP05.csv")

In [47]:
# Variable change files
change22to23 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2023-1yr-api-changes.csv")
change23to24 = pd.read_excel(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\2024-1yr-api-changes.xlsx")

In [48]:
# Variable labels files
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2022.json", 'r') as f:
    data = json.load(f)

labels2022 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2023.json", 'r') as f:
    data = json.load(f)

labels2023 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

labels2024 = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)

### Data

In [49]:
# Look for variable changes between 2022 and 2023
# List with updated variables
change_list_22 = change22to23[change22to23['Change'] == 'Variable Updated']['2022 Variable'].tolist()
# List with variables in 2022
var_list_22 = data2022.columns.tolist()
# Look for variables in 2022 that have change in 2023
updated_list = list(set(var_list_22) & set(change_list_22))
len(updated_list)

48

In [50]:
# DF with equivalent var names
match_vars = change22to23.loc[change22to23['2022 Variable'].isin(updated_list)][['2023 Variable', '2022 Variable']]
match_vars = match_vars.rename(columns = {'2023 Variable': '2023_E', '2022 Variable' : '2022_E'})

match_vars['2023_M'] = match_vars['2023_E'].str[:-1] + 'M'
match_vars['2022_M'] = match_vars['2022_E'].str[:-1] + 'M'

match_vars['2023_PE'] = match_vars['2023_E'].str[:-1] + 'PE'
match_vars['2022_PE'] = match_vars['2022_E'].str[:-1] + 'PE'

match_vars['2023_PM'] = match_vars['2023_E'].str[:-1] + 'PM'
match_vars['2022_PM'] = match_vars['2022_E'].str[:-1] + 'PM'

match_vars

,2023_E,2022_E,2023_M,2022_M,2023_PE,2022_PE,2023_PM,2022_PM
631,DP05_0047E,DP05_0044E,DP05_0047M,DP05_0044M,DP05_0047PE,DP05_0044PE,DP05_0047PM,DP05_0044PM
632,DP05_0048E,DP05_0045E,DP05_0048M,DP05_0045M,DP05_0048PE,DP05_0045PE,DP05_0048PM,DP05_0045PM
633,DP05_0049E,DP05_0046E,DP05_0049M,DP05_0046M,DP05_0049PE,DP05_0046PE,DP05_0049PM,DP05_0046PM
634,DP05_0050E,DP05_0047E,DP05_0050M,DP05_0047M,DP05_0050PE,DP05_0047PE,DP05_0050PM,DP05_0047PM
635,DP05_0051E,DP05_0048E,DP05_0051M,DP05_0048M,DP05_0051PE,DP05_0048PE,DP05_0051PM,DP05_0048PM
636,DP05_0052E,DP05_0049E,DP05_0052M,DP05_0049M,DP05_0052PE,DP05_0049PE,DP05_0052PM,DP05_0049PM
637,DP05_0053E,DP05_0050E,DP05_0053M,DP05_0050M,DP05_0053PE,DP05_0050PE,DP05_0053PM,DP05_0050PM
638,DP05_0054E,DP05_0051E,DP05_0054M,DP05_0051M,DP05_0054PE,DP05_0051PE,DP05_0054PM,DP05_0051PM
639,DP05_0055E,DP05_0052E,DP05_0055M,DP05_0052M,DP05_0055PE,DP05_0052PE,DP05_0055PM,DP05_0052PM
640,DP05_0056E,DP05_0053E,DP05_0056M,DP05_0053M,DP05_0056PE,DP05_0053PE,DP05_0056PM,DP05_0053PM
641,DP05_0057E,DP05_0054E,DP05_0057M,DP05_0054M,DP05_0057PE,DP05_0054PE,DP05_0057PM,DP05_0054PM
642,DP05_0058E,DP05_0055E,DP05_0058M,DP05_0055M,DP05_0058PE,DP05_0055PE,DP05_0058PM,DP05_0055PM
643,DP05_0059E,DP05_0056E,DP05_0059M,DP05_0056M,DP05_0059PE,DP05_0056PE,DP05_0059PM,DP05_0056PM
644,DP05_0060E,DP05_0057E,DP05_0060M,DP05_0057M,DP05_0060PE,DP05_0057PE,DP05_0060PM,DP05_0057PM
645,DP05_0061E,DP05_0058E,DP05_0061M,DP05_0058M,DP05_0061PE,DP05_0058PE,DP05_0061PM,DP05_0058PM
646,DP05_0062E,DP05_0059E,DP05_0062M,DP05_0059M,DP05_0062PE,DP05_0059PE,DP05_0062PM,DP05_0059PM
647,DP05_0063E,DP05_0060E,DP05_0063M,DP05_0060M,DP05_0063PE,DP05_0060PE,DP05_0063PM,DP05_0060PM
648,DP05_0064E,DP05_0061E,DP05_0064M,DP05_0061M,DP05_0064PE,DP05_0061PE,DP05_0064PM,DP05_0061PM
649,DP05_0065E,DP05_0062E,DP05_0065M,DP05_0062M,DP05_0065PE,DP05_0062PE,DP05_0065PM,DP05_0062PM
650,DP05_0066E,DP05_0063E,DP05_0066M,DP05_0063M,DP05_0066PE,DP05_0063PE,DP05_0066PM,DP05_0063PM
651,DP05_0067E,DP05_0064E,DP05_0067M,DP05_0064M,DP05_0067PE,DP05_0064PE,DP05_0067PM,DP05_0064PM
652,DP05_0068E,DP05_0065E,DP05_0068M,DP05_0065M,DP05_0068PE,DP05_0065PE,DP05_0068PM,DP05_0065PM
653,DP05_0069E,DP05_0066E,DP05_0069M,DP05_0066M,DP05_0069PE,DP05_0066PE,DP05_0069PM,DP05_0066PM
654,DP05_0070E,DP05_0067E,DP05_0070M,DP05_0067M,DP05_0070PE,DP05_0067PE,DP05_0070PM,DP05_0067PM
655,DP05_0071E,DP05_0068E,DP05_0071M,DP05_0068M,DP05_0071PE,DP05_0068PE,DP05_0071PM,DP05_0068PM
656,DP05_0072E,DP05_0069E,DP05_0072M,DP05_0069M,DP05_0072PE,DP05_0069PE,DP05_0072PM,DP05_0069PM
657,DP05_0073E,DP05_0070E,DP05_0073M,DP05_0070M,DP05_0073PE,DP05_0070PE,DP05_0073PM,DP05_0070PM
658,DP05_0074E,DP05_0071E,DP05_0074M,DP05_0071M,DP05_0074PE,DP05_0071PE,DP05_0074PM,DP05_0071PM
659,DP05_0075E,DP05_0072E,DP05_0075M,DP05_0072M,DP05_0075PE,DP05_0072PE,DP05_0075PM,DP05_0072PM
660,DP05_0076E,DP05_0073E,DP05_0076M,DP05_0073M,DP05_0076PE,DP05_0073PE,DP05_0076PM,DP05_0073PM
661,DP05_0077E,DP05_0074E,DP05_0077M,DP05_0074M,DP05_0077PE,DP05_0074PE,DP05_0077PM,DP05_0074PM
662,DP05_0078E,DP05_0075E,DP05_0078M,DP05_0075M,DP05_0078PE,DP05_0075PE,DP05_0078PM,DP05_0075PM
663,DP05_0079E,DP05_0076E,DP05_0079M,DP05_0076M,DP05_0079PE,DP05_0076PE,DP05_0079PM,DP05_0076PM
664,DP05_0080E,DP05_0077E,DP05_0080M,DP05_0077M,DP05_0080PE,DP05_0077PE,DP05_0080PM,DP05_0077PM
665,DP05_0081E,DP05_0078E,DP05_0081M,DP05_0078M,DP05_0081PE,DP05_0078PE,DP05_0081PM,DP05_0078PM
666,DP05_0082E,DP05_0079E,DP05_0082M,DP05_0079M,DP05_0082PE,DP05_0079PE,DP05_0082PM,DP05_0079PM
667,DP05_0083E,DP05_0080E,DP05_0083M,DP05_0080M,DP05_0083PE,DP05_0080PE,DP05_0083PM,DP05_0080PM
668,DP05_0084E,DP05_0081E,DP05_0084M,DP05_0081M,DP05_0084PE,DP05_0081PE,DP05_0084PM,DP05_0081PM
669,DP05_0085E,DP05_0082E,DP05_0085M,DP05_0082M,DP05_0085PE,DP05_0082PE,DP05_0085PM,DP05_0082PM
670,DP05_0086E,DP05_0083E,DP05_0086M,DP05_0083M,DP05_0086PE,DP05_0083PE,DP05_0086PM,DP05_0083PM
671,DP05_0087E,DP05_0084E,DP05_0087M,DP05_0084M,DP05_0087PE,DP05_0084PE,DP05_0087PM,DP05_0084PM
672,DP05_0088E,DP05_0085E,DP05_0088M,DP05_0085M,DP05_0088PE,DP05_0085PE,DP05_0088PM,DP05_0085PM
673,DP05_0089E,DP05_0086E,DP05_0089M,DP05_0086M,DP05_0089PE,DP05_0086PE,DP05_0089PM,DP05_0086PM
674,DP05_0090E,DP05_0087E,DP05_0090M,DP05_0087M,DP05_0090PE,DP05_0087PE,DP05_0090PM,DP05_0087PM
675,DP05_0091E,DP05_0088E,DP05_0091M,DP05_0088M,DP05_0091PE,DP05_0088PE,DP05_0091PM,DP05_0088PM
676,DP05_0092E,DP05_0089E,DP05_0092M,DP05_0089M,DP05_0092PE,DP05_0089PE,DP05_0092PM,DP05_0089PM
677,DP05_0093E,DP05_0090E,DP05_0093M,DP05_0090M,DP05_0093PE,DP05_0090PE,DP05_0093PM,DP05_0090PM
678,DP05_0094E,DP05_0091E,DP05_0094M,DP05_0091M,DP05_0094PE,DP05_0091PE,DP05_0094PM,DP05_0091PM

In [51]:
# Equivalent var names to list
match_dic = dict(zip(match_vars['2022_E'], match_vars['2023_E'])) | dict(zip(match_vars['2022_M'], match_vars['2023_M'])) | dict(zip(match_vars['2022_PE'], match_vars['2023_PE'])) | dict(zip(match_vars['2022_PM'], match_vars['2023_PM']))

In [52]:
# Update variable names in 2022
data2022b = data2022.loc[:, ~data2022.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()         # Remove columns not used
data2022b = data2022b.rename(columns = match_dic )                                              # Update names
data2022b

,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,DP05_0003M,...,DP05_0094M,DP05_0094PE,DP05_0094PM,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,141787,9279,141787,-888888888,66520,6280,46.9,2.5,75267,5328,...,4931,53.5,2.6,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP05)
1,112582,9026,112582,-888888888,59887,6069,53.2,3.5,52695,5949,...,4625,45.6,4.0,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP05)
2,226989,14071,226989,-888888888,109516,8192,48.2,2.1,117473,8742,...,6610,52.0,2.5,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP05)
3,206975,12047,206975,-888888888,93596,6771,45.2,2.0,113379,7918,...,5938,55.8,2.1,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP05)
4,105801,9870,105801,-888888888,52095,5882,49.2,3.4,53706,6292,...,4253,52.0,3.2,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP05)
5,138953,10888,138953,-888888888,63845,7684,45.9,3.4,75108,6571,...,5037,56.8,3.1,795P200US3604110,NYC-Manhattan Community District 10--Harlem PU...,36,4110,2022,acs1,group(DP05)
6,128317,10966,128317,-888888888,64280,6638,50.1,2.7,64037,6350,...,4145,52.1,2.8,795P200US3604111,NYC-Manhattan Community District 11--East Harl...,36,4111,2022,acs1,group(DP05)
7,202678,14491,202678,-888888888,95645,7971,47.2,2.1,107033,8846,...,5812,52.6,2.7,795P200US3604112,NYC-Manhattan Community District 12--Washingto...,36,4112,2022,acs1,group(DP05)
8,149102,10893,149102,-888888888,72124,6344,48.4,2.4,76978,6699,...,5704,52.0,2.6,795P200US3604121,NYC-Manhattan Community Districts 1 & 2--Finan...,36,4121,2022,acs1,group(DP05)
9,183089,10086,183089,-888888888,85511,5227,46.7,2.1,97578,7415,...,6574,55.3,2.3,795P200US3604165,NYC-Manhattan Community Districts 5 & 6--Midto...,36,4165,2022,acs1,group(DP05)
10,139747,13378,139747,-888888888,66059,7622,47.3,2.9,73688,7970,...,5094,57.4,3.3,795P200US3604204,NYC-Bronx Community District 4--Highbridge & C...,36,4204,2022,acs1,group(DP05)
11,114828,10694,114828,-888888888,52799,5859,46.0,2.8,62029,6574,...,3725,53.9,4.2,795P200US3604205,NYC-Bronx Community District 5--Morris Heights...,36,4205,2022,acs1,group(DP05)
12,132380,10941,132380,-888888888,64548,6555,48.8,2.3,67832,5881,...,3765,56.4,3.3,795P200US3604207,"NYC-Bronx Community District 7--Fordham, Bedfo...",36,4207,2022,acs1,group(DP05)
13,87280,7235,87280,-888888888,40104,4130,45.9,2.5,47176,4303,...,2944,55.7,3.0,795P200US3604208,"NYC-Bronx Community District 8--Riverdale, Kin...",36,4208,2022,acs1,group(DP05)
14,184743,14704,184743,-888888888,89326,8432,48.4,2.3,95417,8543,...,5331,53.2,2.6,795P200US3604209,NYC-Bronx Community District 9--Soundview & Pa...,36,4209,2022,acs1,group(DP05)
15,136930,12105,136930,-888888888,62306,6626,45.5,2.7,74624,7636,...,4774,55.1,2.5,795P200US3604210,NYC-Bronx Community District 10--Co-op City & ...,36,4210,2022,acs1,group(DP05)
16,114874,10268,114874,-888888888,55435,6191,48.3,2.9,59439,5992,...,4028,53.1,3.1,795P200US3604211,NYC-Bronx Community District 11--Pelham Parkwa...,36,4211,2022,acs1,group(DP05)
17,153790,12448,153790,-888888888,76807,7297,49.9,2.7,76983,7641,...,5136,53.3,2.9,795P200US3604212,"NYC-Bronx Community District 12--Wakefield, Wi...",36,4212,2022,acs1,group(DP05)
18,146382,12088,146382,-888888888,67698,6863,46.2,2.7,78684,7642,...,5173,55.5,3.3,795P200US3604221,"NYC-Bronx Community Districts 1 & 2--Melrose, ...",36,4221,2022,acs1,group(DP05)
19,168992,14222,168992,-888888888,78197,8027,46.3,2.6,90795,8654,...,5785,56.0,3.5,795P200US3604263,NYC-Bronx Community Districts 3 & 6--Morrisani...,36,4263,2022,acs1,group(DP05)
20,186944,11915,186944,-888888888,89819,6854,48.0,2.4,97125,8057,...,5339,52.4,2.4,795P200US3604301,NYC-Brooklyn Community District 1--Williamsbur...,36,4301,2022,acs1,group(DP05)
21,135987,10439,135987,-888888888,60155,5352,44.2,1.9,75832,6274,...,4402,56.9,2.3,795P200US3604302,NYC-Brooklyn Community District 2--Downtown Br...,36,4302,2022,acs1,group(DP05)
22,166380,13908,166380,-888888888,82520,8466,49.6,2.0,83860,6887,...,4801,52.4,2.5,795P200US3604303,NYC-Brooklyn Community District 3--Bedford-Stu...,36,4303,2022,acs1,group(DP05)
23,94423,9726,94423,-888888888,44829,5989,47.5,3.3,49594,5457,...,3835,55.8,3.8,795P200US3604304,NYC-Brooklyn Community District 4--Bushwick PU...,36,4304,2022,acs1,group(DP05)
24,200828,14883,200828,-888888888,93104,8615,46.4,2.2,107724,8680,...,5334,57.0,2.5,795P200US3604305,NYC-Brooklyn Community District 5--East New Yo...,36,4305,2022,acs1,group(DP05)
25,107930,8990,107930,-888888888,51682,5109,47.9,2.0,56248,4852,...,3043,52.6,2.5,795P200US3604306,NYC-Brooklyn Community District 6--Park Slope ...,36,4306,2022,acs1,group(DP05)
26,129890,8585,129890,-888888888,64552,5029,49.7,1.7,65338,4609,...,2802,51.7,2.4,795P200US3604307,NYC-Brooklyn Community District 7--Sunset Park...,36,4307,2022,acs1,group(DP05)
27,107419,10247,107419,-888888888,49595,5526,46.2,2.4,57824,5982,...,4146,55.4,3.1,795P200US3604308,NYC-Brooklyn Community District 8--Crown Heigh...,36,4308,2022,acs1,group(DP05)
28,94109,8596,94109,-888888888,44646,4925,47.4,2.9,49463,5217,...,3653,53.7,3.9,795P200US3604309,NYC-Brooklyn Community District 9--Crown Heigh...,36,4309,2022,acs1,group(DP05)
29,116696,9182,116696,-888888888,55025,4937,47.2,2.2,61671,5563,...,2921,52.5,2.1,795P200US3604310,NYC-Brooklyn Community District 10--Bay Ridge ...,36,4310,2022,acs1,group(DP05)
30,184415,13432,184415,-888888888,92000,7527,49.9,1.7,92415,7285,...,4742,51.3,1.6,795P200US3604311,NYC-Brooklyn Community District 11--Bensonhurs...,36,4311,2022,acs1,group(DP05)
31,191368,14346,191368,-888888888,94987,7973,49.6,1.6,96381,7627,...,3728,51.6,2.1,795P200US3604312,NYC-Brooklyn Community District 12--Borough Pa...,36,4312,2022,acs1,group(DP05)
32,119482,11637,119482,-888888888,57006,6825,47.7,2.6,62476,6307,...,4065,54.3,3.2,795P200US3604313,NYC-Brooklyn Community District 13--Coney Isla...,36,4313,2022,acs1,group(DP05)
33,152340,10550,152340,-888888888,70758,5829,46.4,1.9,81582,6158,...,4959,54.1,2.4,795P200US3604314,NYC-Brooklyn Community District 14--Flatbush &...,36,4314,2022,acs1,group(DP05)
34,151970,9923,151970,-888888888,74853,4870,49.3,1.5,77117,6057,...,3972,52.3,1.8,795P200US3604315,NYC-Brooklyn Community District 15--Sheepshead...,36,4315,2022,acs1,group(DP05)
35,99827,11224,99827,-888888888,48134,6618,48.2,3.1,51693,6150,...,4125,54.8,4.0,795P200US3604316,NYC-Brooklyn Community District 16--Ocean Hill...,36,4316,2022,acs1,group(DP05)
36,160620,10234,160620,-888888888,73668,6799,45.9,2.4,86952,5861,...,4341,56.9,2.5,795P200US3604317,NYC-Brooklyn Community District 17--East Flatb...,36,4317,2022,acs1,group(DP05)
37,189888,10069,189888,-888888888,87674,5109,46.2,1.6,102214,6618,...,4392,54.5,1.8,795P200US3604318,NYC-Brooklyn Community District 18--Canarsie &...,36,4318,2022,acs1,group(DP05)
38,177115,10140,177115,-888888888,91094,5843,51.4,1.6,86021,5831,...,4725,50.6,2.2,795P200US3604401,NYC-Queens Community District 1--Astoria & Que...,36,4401,2022,acs1,group(DP05)
39,125926,10539,125926,-888888888,62972,5025,50.0,2.7,62954,7309,...,4204,49.5,3.9,795P200US3604402,NYC-Queens Community District 2--Long Island C...,36,4402,2022,acs1,group(DP05)
40,162686,12318,162686,-888888888,85260,6867,52.4,1.8,77426,6811,...,3631,49.1,2.6,795P200US3604403,NYC-Queens Community District 3--Jackson Heigh...,36,4403,2022,acs1,group(DP05)
41,160534,10643,160534,-888888888,83068,6851,51.7,2.3,77466,6145,...,3468,52.8,2.8,795P200US3604404,NYC-Queens Community District 4--Elmhurst & Co...,36,4404,2022,acs1,group(DP05)
42,175992,11971,175992,-888888888,87728,6520,49.8,1.6,88264,6682,...,4130,52.6,1.7,795P200US3604405,"NYC-Queens Community District 5--Ridgewood, Ma...",36,4405,2022,acs1,group(DP05)
43,128592,10883,128592,-888888888,58426,6157,45.4,2.2,70166,6064,...,4144,54.8,2.2,795P200US3604406,NYC-Queens Community District 6--Forest Hills ...,36,4406,2022,acs1,group(DP05)
44,246851,12046,246851,-888888888,117098,6927,47.4,1.5,129753,7265,...,5201,53.6,1.8,795P200US3604407,"NYC-Queens Community District 7--Flushing, Mur...",36,4407,2022,acs1,group(DP05)
45,148045,11744,148045,-888888888,69050,6237,46.6,1.9,78995,6794,...,4675,53.0,2.2,795P200US3604408,NYC-Queens Community District 8--Fresh Meadows...,36,4408,2022,acs1,group(DP05)
46,136313,8246,136313,-888888888,68678,5061,50.4,1.6,67635,4268,...,3184,52.2,2.0,795P200US3604409,"NYC-Queens Community District 9--Kew Gardens, ...",36,4409,2022,acs1,group(DP05)
47,129072,10016,129072,-888888888,62997,5460,48.8,1.7,66075,5458,...,4452,52.3,2.1,795P200US3604410,NYC-Queens Community District 10--South Ozone ...,36,4410,2022,acs1,group(DP05)
48,118293,9417,118293,-888888888,56996,5273,48.2,2.1,61297,5337,...,3234,51.7,2.4,795P200US3604411,"NYC-Queens Community District 11--Auburndale, ...",36,4411,2022,acs1,group(DP05)
49,248158,12962,248158,-888888888,117121,7006,47.2,1.3,131037,7571,...,4985,54.2,1.7,795P200US3604412,"NYC-Queens Community District 12--Jamaica, St....",36,4412,2022,acs1,group(DP05)
50,193823,11409,193823,-888888888,91980,6021,47.5,1.3,101843,6444,...,4907,53.4,1.6,795P200US3604413,NYC-Queens Community District 13--Queens Villa...,36,4413,2022,acs1,group(DP05)
51,126629,11227,126629,-888888888,62253,5940,49.2,2.7,64376,7149,...,4913,52.2,3.4,795P200US3604414,NYC-Queens Community District 14--The Rockaway...,36,4414,2022,acs1,group(DP05)
52,184556,9508,184556,-888888888,89415,5377,48.4,1.3,95141,5197,...,3973,52.7,1.5,795P200US3604501,NYC-Staten Island Community District 1--North ...,36,4501,2022,acs1,group(DP05)
53,145506,9975,145506,-888888888,74052,5769,50.9,1.7,71454,5377,...,3998,51.4,1.8,795P200US3604502,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2022,acs1,group(DP05)
54,161071,9820,161071,-888888888,77863,5173,48.3,1.5,83208,5732,...,3948,51.3,1.6,795P200US3604503,NYC-Staten Island Community District 3--South ...,36,4503,2022,acs1,group(DP05)

In [53]:
# Concat dataframes 2022 + 2023
data2023b = data2023.loc[:, ~data2023.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()         # Remove columns not used
all_data = pd.concat([data2022b, data2023b], ignore_index = True)
all_data.head()

,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,DP05_0003M,...,DP05_0044PE,DP05_0044PM,DP05_0045E,DP05_0045M,DP05_0045PE,DP05_0045PM,DP05_0046E,DP05_0046M,DP05_0046PE,DP05_0046PM
0,141787,9279,141787,-888888888,66520,6280,46.9,2.5,75267,5328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,112582,9026,112582,-888888888,59887,6069,53.2,3.5,52695,5949,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,226989,14071,226989,-888888888,109516,8192,48.2,2.1,117473,8742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,206975,12047,206975,-888888888,93596,6771,45.2,2.0,113379,7918,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105801,9870,105801,-888888888,52095,5882,49.2,3.4,53706,6292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
# Look for variable changes between 2022 and 2023
# List with updated variables
change_list_23 = change23to24[change23to24['Change'] == 'Variable Updated']['2023 Variable'].tolist()
# List with variables in 2022
var_list_23 = data2023.columns.tolist()
# Look for variables in 2022 that have change in 2023
updated_list = list(set(var_list_23) & set(change_list_23))
len(updated_list)

57

In [55]:
# Look for variable changes between 2023 and 2024
# List with updated variables
change_list_23 = change23to24[change23to24['Change'] == 'Variable Updated']['2023 Variable'].tolist()
# List with variables in 2022
var_list_23 = all_data.columns.tolist()                                                                     # Note, using all_data since columns are using 2023 names
# Look for variables in 2022 that have change in 2023
updated_list = list(set(var_list_23) & set(change_list_23))
len(updated_list)

57

In [56]:
# DF with equivalent var names
match_vars = change23to24.loc[change23to24['2023 Variable'].isin(updated_list)][['2024 Variable', '2023 Variable']]
match_vars = match_vars.rename(columns = {'2024 Variable': '2024_E', '2023 Variable' : '2023_E'})

match_vars['2024_M'] = match_vars['2024_E'].str[:-1] + 'M'
match_vars['2023_M'] = match_vars['2023_E'].str[:-1] + 'M'

match_vars['2024_PE'] = match_vars['2024_E'].str[:-1] + 'PE'
match_vars['2023_PE'] = match_vars['2023_E'].str[:-1] + 'PE'

match_vars['2024_PM'] = match_vars['2024_E'].str[:-1] + 'PM'
match_vars['2023_PM'] = match_vars['2023_E'].str[:-1] + 'PM'

match_vars

,2024_E,2023_E,2024_M,2023_M,2024_PE,2023_PE,2024_PM,2023_PM
625,DP05_0045E,DP05_0038E,DP05_0045M,DP05_0038M,DP05_0045PE,DP05_0038PE,DP05_0045PM,DP05_0038PM
626,DP05_0053E,DP05_0039E,DP05_0053M,DP05_0039M,DP05_0053PE,DP05_0039PE,DP05_0053PM,DP05_0039PM
627,DP05_0054E,DP05_0040E,DP05_0054M,DP05_0040M,DP05_0054PE,DP05_0040PE,DP05_0054PM,DP05_0040PM
628,DP05_0055E,DP05_0041E,DP05_0055M,DP05_0041M,DP05_0055PE,DP05_0041PE,DP05_0055PM,DP05_0041PM
629,DP05_0056E,DP05_0042E,DP05_0056M,DP05_0042M,DP05_0056PE,DP05_0042PE,DP05_0056PM,DP05_0042PM
630,DP05_0057E,DP05_0043E,DP05_0057M,DP05_0043M,DP05_0057PE,DP05_0043PE,DP05_0057PM,DP05_0043PM
631,DP05_0058E,DP05_0044E,DP05_0058M,DP05_0044M,DP05_0058PE,DP05_0044PE,DP05_0058PM,DP05_0044PM
632,DP05_0059E,DP05_0045E,DP05_0059M,DP05_0045M,DP05_0059PE,DP05_0045PE,DP05_0059PM,DP05_0045PM
633,DP05_0060E,DP05_0046E,DP05_0060M,DP05_0046M,DP05_0060PE,DP05_0046PE,DP05_0060PM,DP05_0046PM
634,DP05_0061E,DP05_0047E,DP05_0061M,DP05_0047M,DP05_0061PE,DP05_0047PE,DP05_0061PM,DP05_0047PM
635,DP05_0062E,DP05_0048E,DP05_0062M,DP05_0048M,DP05_0062PE,DP05_0048PE,DP05_0062PM,DP05_0048PM
636,DP05_0063E,DP05_0049E,DP05_0063M,DP05_0049M,DP05_0063PE,DP05_0049PE,DP05_0063PM,DP05_0049PM
637,DP05_0064E,DP05_0050E,DP05_0064M,DP05_0050M,DP05_0064PE,DP05_0050PE,DP05_0064PM,DP05_0050PM
638,DP05_0065E,DP05_0051E,DP05_0065M,DP05_0051M,DP05_0065PE,DP05_0051PE,DP05_0065PM,DP05_0051PM
639,DP05_0066E,DP05_0052E,DP05_0066M,DP05_0052M,DP05_0066PE,DP05_0052PE,DP05_0066PM,DP05_0052PM
640,DP05_0067E,DP05_0053E,DP05_0067M,DP05_0053M,DP05_0067PE,DP05_0053PE,DP05_0067PM,DP05_0053PM
641,DP05_0068E,DP05_0054E,DP05_0068M,DP05_0054M,DP05_0068PE,DP05_0054PE,DP05_0068PM,DP05_0054PM
642,DP05_0069E,DP05_0055E,DP05_0069M,DP05_0055M,DP05_0069PE,DP05_0055PE,DP05_0069PM,DP05_0055PM
643,DP05_0070E,DP05_0056E,DP05_0070M,DP05_0056M,DP05_0070PE,DP05_0056PE,DP05_0070PM,DP05_0056PM
644,DP05_0071E,DP05_0057E,DP05_0071M,DP05_0057M,DP05_0071PE,DP05_0057PE,DP05_0071PM,DP05_0057PM
645,DP05_0072E,DP05_0058E,DP05_0072M,DP05_0058M,DP05_0072PE,DP05_0058PE,DP05_0072PM,DP05_0058PM
646,DP05_0073E,DP05_0059E,DP05_0073M,DP05_0059M,DP05_0073PE,DP05_0059PE,DP05_0073PM,DP05_0059PM
647,DP05_0074E,DP05_0060E,DP05_0074M,DP05_0060M,DP05_0074PE,DP05_0060PE,DP05_0074PM,DP05_0060PM
648,DP05_0075E,DP05_0061E,DP05_0075M,DP05_0061M,DP05_0075PE,DP05_0061PE,DP05_0075PM,DP05_0061PM
649,DP05_0076E,DP05_0062E,DP05_0076M,DP05_0062M,DP05_0076PE,DP05_0062PE,DP05_0076PM,DP05_0062PM
650,DP05_0077E,DP05_0063E,DP05_0077M,DP05_0063M,DP05_0077PE,DP05_0063PE,DP05_0077PM,DP05_0063PM
651,DP05_0078E,DP05_0064E,DP05_0078M,DP05_0064M,DP05_0078PE,DP05_0064PE,DP05_0078PM,DP05_0064PM
652,DP05_0079E,DP05_0065E,DP05_0079M,DP05_0065M,DP05_0079PE,DP05_0065PE,DP05_0079PM,DP05_0065PM
653,DP05_0080E,DP05_0066E,DP05_0080M,DP05_0066M,DP05_0080PE,DP05_0066PE,DP05_0080PM,DP05_0066PM
654,DP05_0081E,DP05_0067E,DP05_0081M,DP05_0067M,DP05_0081PE,DP05_0067PE,DP05_0081PM,DP05_0067PM
655,DP05_0082E,DP05_0068E,DP05_0082M,DP05_0068M,DP05_0082PE,DP05_0068PE,DP05_0082PM,DP05_0068PM
656,DP05_0083E,DP05_0069E,DP05_0083M,DP05_0069M,DP05_0083PE,DP05_0069PE,DP05_0083PM,DP05_0069PM
657,DP05_0084E,DP05_0070E,DP05_0084M,DP05_0070M,DP05_0084PE,DP05_0070PE,DP05_0084PM,DP05_0070PM
658,DP05_0085E,DP05_0071E,DP05_0085M,DP05_0071M,DP05_0085PE,DP05_0071PE,DP05_0085PM,DP05_0071PM
659,DP05_0086E,DP05_0072E,DP05_0086M,DP05_0072M,DP05_0086PE,DP05_0072PE,DP05_0086PM,DP05_0072PM
660,DP05_0087E,DP05_0073E,DP05_0087M,DP05_0073M,DP05_0087PE,DP05_0073PE,DP05_0087PM,DP05_0073PM
661,DP05_0088E,DP05_0074E,DP05_0088M,DP05_0074M,DP05_0088PE,DP05_0074PE,DP05_0088PM,DP05_0074PM
662,DP05_0089E,DP05_0075E,DP05_0089M,DP05_0075M,DP05_0089PE,DP05_0075PE,DP05_0089PM,DP05_0075PM
663,DP05_0090E,DP05_0076E,DP05_0090M,DP05_0076M,DP05_0090PE,DP05_0076PE,DP05_0090PM,DP05_0076PM
664,DP05_0091E,DP05_0077E,DP05_0091M,DP05_0077M,DP05_0091PE,DP05_0077PE,DP05_0091PM,DP05_0077PM
665,DP05_0092E,DP05_0078E,DP05_0092M,DP05_0078M,DP05_0092PE,DP05_0078PE,DP05_0092PM,DP05_0078PM
666,DP05_0093E,DP05_0079E,DP05_0093M,DP05_0079M,DP05_0093PE,DP05_0079PE,DP05_0093PM,DP05_0079PM
667,DP05_0094E,DP05_0080E,DP05_0094M,DP05_0080M,DP05_0094PE,DP05_0080PE,DP05_0094PM,DP05_0080PM
668,DP05_0095E,DP05_0081E,DP05_0095M,DP05_0081M,DP05_0095PE,DP05_0081PE,DP05_0095PM,DP05_0081PM
669,DP05_0096E,DP05_0082E,DP05_0096M,DP05_0082M,DP05_0096PE,DP05_0082PE,DP05_0096PM,DP05_0082PM
670,DP05_0097E,DP05_0083E,DP05_0097M,DP05_0083M,DP05_0097PE,DP05_0083PE,DP05_0097PM,DP05_0083PM
671,DP05_0098E,DP05_0084E,DP05_0098M,DP05_0084M,DP05_0098PE,DP05_0084PE,DP05_0098PM,DP05_0084PM
672,DP05_0099E,DP05_0085E,DP05_0099M,DP05_0085M,DP05_0099PE,DP05_0085PE,DP05_0099PM,DP05_0085PM
673,DP05_0100E,DP05_0086E,DP05_0100M,DP05_0086M,DP05_0100PE,DP05_0086PE,DP05_0100PM,DP05_0086PM
674,DP05_0101E,DP05_0087E,DP05_0101M,DP05_0087M,DP05_0101PE,DP05_0087PE,DP05_0101PM,DP05_0087PM
675,DP05_0102E,DP05_0088E,DP05_0102M,DP05_0088M,DP05_0102PE,DP05_0088PE,DP05_0102PM,DP05_0088PM
676,DP05_0103E,DP05_0089E,DP05_0103M,DP05_0089M,DP05_0103PE,DP05_0089PE,DP05_0103PM,DP05_0089PM
677,DP05_0104E,DP05_0090E,DP05_0104M,DP05_0090M,DP05_0104PE,DP05_0090PE,DP05_0104PM,DP05_0090PM
678,DP05_0105E,DP05_0091E,DP05_0105M,DP05_0091M,DP05_0105PE,DP05_0091PE,DP05_0105PM,DP05_0091PM
679,DP05_0106E,DP05_0092E,DP05_0106M,DP05_0092M,DP05_0106PE,DP05_0092PE,DP05_0106PM,DP05_0092PM
680,DP05_0107E,DP05_0093E,DP05_0107M,DP05_0093M,DP05_0107PE,DP05_0093PE,DP05_0107PM,DP05_0093PM
681,DP05_0108E,DP05_0094E,DP05_0108M,DP05_0094M,DP05_0108PE,DP05_0094PE,DP05_0108PM,DP05_0094PM

In [57]:
# List with equivalent var names
match_dic = dict(zip(match_vars['2023_E'], match_vars['2024_E'])) | dict(zip(match_vars['2023_M'], match_vars['2024_M'])) | dict(zip(match_vars['2023_PE'], match_vars['2024_PE'])) | dict(zip(match_vars['2023_PM'], match_vars['2024_PM']))

In [58]:
# Update var names in 2023 & 2022 appended df
all_data = all_data.rename(columns = match_dic )
all_data

,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,DP05_0003M,...,DP05_0058PE,DP05_0058PM,DP05_0059E,DP05_0059M,DP05_0059PE,DP05_0059PM,DP05_0060E,DP05_0060M,DP05_0060PE,DP05_0060PM
0,141787,9279,141787,-888888888,66520,6280,46.9,2.5,75267,5328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,112582,9026,112582,-888888888,59887,6069,53.2,3.5,52695,5949,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,226989,14071,226989,-888888888,109516,8192,48.2,2.1,117473,8742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,206975,12047,206975,-888888888,93596,6771,45.2,2.0,113379,7918,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105801,9870,105801,-888888888,52095,5882,49.2,3.4,53706,6292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,197195,11446,197195,-888888888,92853,6720,47.1,1.8,104342,6839,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0
106,117189,12423,117189,-888888888,53081,6625,45.3,2.5,64108,7130,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0
107,167916,8222,167916,-888888888,81536,4842,48.6,1.4,86380,4643,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0
108,142150,10116,142150,-888888888,70120,6115,49.3,1.6,72030,4892,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0
109,180621,10741,180621,-888888888,88459,5882,49.0,1.3,92162,5800,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0

In [59]:
# Concat dataframes
data2024b = data2024.loc[:, ~data2024.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()     # Remove columns not used
all_data = pd.concat([all_data, data2024b], ignore_index = True)                            # Concat
all_data.sort_index(axis = 1)                                                               # sort columns
all_data.head()

,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,DP05_0003M,...,DP05_0050PE,DP05_0050PM,DP05_0051E,DP05_0051M,DP05_0051PE,DP05_0051PM,DP05_0052E,DP05_0052M,DP05_0052PE,DP05_0052PM
0,141787,9279,141787,-888888888,66520,6280,46.9,2.5,75267,5328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,112582,9026,112582,-888888888,59887,6069,53.2,3.5,52695,5949,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,226989,14071,226989,-888888888,109516,8192,48.2,2.1,117473,8742,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,206975,12047,206975,-888888888,93596,6771,45.2,2.0,113379,7918,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105801,9870,105801,-888888888,52095,5882,49.2,3.4,53706,6292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Labels

In [60]:
# List with no-match variables from 2022 to 2023
no_match_list_2022 = change22to23[(change22to23['Change'] == 'No Match') & (change22to23['Table ID'] == 'DP05')]['2022 Variable'].tolist()
no_match_list_2022

['DP05_0040E', 'DP05_0041E', 'DP05_0042E', 'DP05_0043E']

In [61]:
# Keep non-match labels
no_match_labels_2022 = labels2022[labels2022['variable'].isin(no_match_list_2022)]
no_match_labels_2022

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
1136,DP05_0040E,Estimate!!RACE!!Total population!!One race!!Am...,ACS Demographic and Housing Estimates,int,DP05,0,NaN,NaN,"DP05_0040EA,DP05_0040M,DP05_0040MA",NaN
1143,DP05_0041E,Estimate!!RACE!!Total population!!One race!!Am...,ACS Demographic and Housing Estimates,int,DP05,0,NaN,NaN,"DP05_0041EA,DP05_0041M,DP05_0041MA",NaN
1148,DP05_0042E,Estimate!!RACE!!Total population!!One race!!Am...,ACS Demographic and Housing Estimates,int,DP05,0,NaN,NaN,"DP05_0042EA,DP05_0042M,DP05_0042MA",NaN
1152,DP05_0043E,Estimate!!RACE!!Total population!!One race!!Am...,ACS Demographic and Housing Estimates,int,DP05,0,NaN,NaN,"DP05_0043EA,DP05_0043M,DP05_0043MA",NaN

In [62]:
# List with no-match variables from 2023 to 2024
no_match_list_2023 = change23to24[(change23to24['Change'] == 'No Match') & (change23to24['Table ID'] == 'DP05')]['2023 Variable'].tolist()
no_match_list_2023

[]

In [63]:
# Keep non-match labels
no_match_labels_2023 = labels2023[labels2023['variable'].isin(no_match_list_2023)]
no_match_labels_2023

Empty DataFrame
Columns: [variable, label, concept, predicateType, group, limit, predicateOnly, hasGeoCollectionSupport, attributes, required]
Index: []

In [64]:
# Start with 2024 labels and no-match labels from previous years
all_labels = pd.concat([labels2024, no_match_labels_2022, no_match_labels_2023], ignore_index=True)

In [65]:
# Keep only DP05 labels
all_labels = all_labels[all_labels['group'] == 'DP05'].copy()
all_labels.head()

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
4,DP05_0050PE,Percent!!RACE!!Total population!!One race!!Bla...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0050PEA,DP05_0050PM,DP05_0050PMA",NaN
18,DP05_0094PE,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0094PEA,DP05_0094PM,DP05_0094PMA",NaN
27,DP05_0104PE,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0104PEA,DP05_0104PM,DP05_0104PMA",NaN
45,DP05_0028E,Estimate!!SEX AND AGE!!Total population!!18 ye...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0028EA,DP05_0028M,DP05_0028MA",NaN
46,DP05_0028PE,Percent!!SEX AND AGE!!Total population!!18 yea...,ACS Demographic and Housing Estimates,int,DP05,0,NaN,NaN,"DP05_0028PEA,DP05_0028PM,DP05_0028PMA",NaN

In [66]:
# Format variable labels
meta_labels_df = all_labels[['variable', 'label', 'group']]                                                     # Select only necessary columns
meta_labels_df = meta_labels_df.rename(columns = {'variable' : 'var_name'})                                     # Change column names
meta_labels_df['var_type'] = meta_labels_df['var_name'].str.extract(r'\d+([A-Z]+)', expand=False)               # Gen var type
meta_labels_df['var_type'] = meta_labels_df['var_type'].replace({'E': 'Estimate','PE': 'Percentage'})           # Change type description
meta_labels_df['var_label'] = meta_labels_df['label'].replace('Estimate|Percent', '', regex=True)               # Gen base label
meta_labels_df = meta_labels_df.drop_duplicates()                                                               # Drop possible duplicates
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.lstrip('!!')                                      # Remove initial '!!'
meta_labels_df['var_topic'] = meta_labels_df['var_label'].str.split('!!').str[0]                                # Add var topic
meta_labels_df['var_label'] = meta_labels_df['var_label'].str.replace('!!', ' - ', regex=True)                  # Remove other '!!'
meta_labels_df['var_attributes'] = meta_labels_df['var_name'].str[:-1] + 'M (marging of error)'                 # Gen column with var attributes
meta_labels_df = meta_labels_df[['var_name', 'var_type', 'var_topic', 'var_label', 'var_attributes', 'group']]  # Re-order columns
meta_labels_df = meta_labels_df.sort_values(by = 'var_name')                                                    # Sort values by var_name
meta_labels_df

,var_name,var_type,var_topic,var_label,var_attributes,group
435,DP05_0001E,Estimate,SEX AND AGE,SEX AND AGE - Total population,DP05_0001M (marging of error),DP05
647,DP05_0001PE,Percentage,SEX AND AGE,SEX AND AGE - Total population,DP05_0001PM (marging of error),DP05
443,DP05_0002E,Estimate,SEX AND AGE,SEX AND AGE - Total population - Male,DP05_0002M (marging of error),DP05
80,DP05_0002PE,Percentage,SEX AND AGE,SEX AND AGE - Total population - Male,DP05_0002PM (marging of error),DP05
447,DP05_0003E,Estimate,SEX AND AGE,SEX AND AGE - Total population - Female,DP05_0003M (marging of error),DP05
...,...,...,...,...,...,...
1063,DP05_0106PE,Percentage,"CITIZEN, VOTING AGE POPULATION","CITIZEN, VOTING AGE POPULATION - Citizen, 18 a...",DP05_0106PM (marging of error),DP05
1257,DP05_0107E,Estimate,"CITIZEN, VOTING AGE POPULATION","CITIZEN, VOTING AGE POPULATION - Citizen, 18 a...",DP05_0107M (marging of error),DP05
1237,DP05_0107PE,Percentage,"CITIZEN, VOTING AGE POPULATION","CITIZEN, VOTING AGE POPULATION - Citizen, 18 a...",DP05_0107PM (marging of error),DP05
1268,DP05_0108E,Estimate,"CITIZEN, VOTING AGE POPULATION","CITIZEN, VOTING AGE POPULATION - Citizen, 18 a...",DP05_0108M (marging of error),DP05
1401,DP05_0108PE,Percentage,"CITIZEN, VOTING AGE POPULATION","CITIZEN, VOTING AGE POPULATION - Citizen, 18 a...",DP05_0108PM (marging of error),DP05

### Save Data

In [67]:
# Save data
data_sample = 'acs1'
data_geography = 'PUMA'
data_group = 'DP05'
group_desc = 'DEMOGRAPHIC_CHAR'


directory = fr'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\{data_sample}\panel\{data_geography}'
file_name = f'{data_sample}_paneL_2024_{data_geography}_NYC_{data_group}_{group_desc}.xlsx'

# Ensure the folder exists (create if missing)
os.makedirs(directory, exist_ok=True)


full_path = os.path.join(directory, file_name)

with pd.ExcelWriter(full_path) as writer:
    var_df.to_excel(writer, sheet_name = 'data', index = False)
    meta_labels_df.to_excel(writer, sheet_name = 'var_labels', index = False)