# Format acs tables

In [ ]:
import numpy as np
import json
import pandas as pd

In [20]:
with open(r"C:\Users\ro_he\OneDrive\NYC OMB\Projects\ACS Warehouse\data\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

In [21]:
df = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)
df

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
0,for,Census API FIPS 'for' clause,Census API Geography Specification,fips-for,N/A,0,True,NaN,NaN,NaN
1,in,Census API FIPS 'in' clause,Census API Geography Specification,fips-in,N/A,0,True,NaN,NaN,NaN
2,ucgid,Uniform Census Geography Identifier clause,Census API Geography Specification,ucgid,N/A,0,True,True,NaN,NaN
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN
4,DP05_0050PE,Percent!!RACE!!Total population!!One race!!Bla...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0050PEA,DP05_0050PM,DP05_0050PMA",NaN
...,...,...,...,...,...,...,...,...,...,...
1412,DP03_0039PE,Percent!!INDUSTRY!!Civilian employed populatio...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0039PEA,DP03_0039PM,DP03_0039PMA",NaN
1413,DP02_0098E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0098EA,DP02_0098M,DP02_0098MA",NaN
1414,DP04_0095PE,Percent!!SELECTED MONTHLY OWNER COSTS (SMOC)!!...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0095PEA,DP04_0095PM,DP04_0095PMA",NaN
1415,DP02_0036PE,Percent!!MARITAL STATUS!!Females 15 years and ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0036PEA,DP02_0036PM,DP02_0036PMA",NaN
1416,DP05_0098PE,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0098PEA,DP05_0098PM,DP05_0098PMA",NaN

In [22]:
df["attributes_list"] = (
    df["attributes"]
      .fillna("")
      .str.split(",")
)
df

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required,attributes_list
0,for,Census API FIPS 'for' clause,Census API Geography Specification,fips-for,N/A,0,True,NaN,NaN,NaN,[]
1,in,Census API FIPS 'in' clause,Census API Geography Specification,fips-in,N/A,0,True,NaN,NaN,NaN,[]
2,ucgid,Uniform Census Geography Identifier clause,Census API Geography Specification,ucgid,N/A,0,True,True,NaN,NaN,[]
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN,"[DP02_0126EA, DP02_0126M, DP02_0126MA]"
4,DP05_0050PE,Percent!!RACE!!Total population!!One race!!Bla...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0050PEA,DP05_0050PM,DP05_0050PMA",NaN,"[DP05_0050PEA, DP05_0050PM, DP05_0050PMA]"
...,...,...,...,...,...,...,...,...,...,...,...
1412,DP03_0039PE,Percent!!INDUSTRY!!Civilian employed populatio...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0039PEA,DP03_0039PM,DP03_0039PMA",NaN,"[DP03_0039PEA, DP03_0039PM, DP03_0039PMA]"
1413,DP02_0098E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0098EA,DP02_0098M,DP02_0098MA",NaN,"[DP02_0098EA, DP02_0098M, DP02_0098MA]"
1414,DP04_0095PE,Percent!!SELECTED MONTHLY OWNER COSTS (SMOC)!!...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0095PEA,DP04_0095PM,DP04_0095PMA",NaN,"[DP04_0095PEA, DP04_0095PM, DP04_0095PMA]"
1415,DP02_0036PE,Percent!!MARITAL STATUS!!Females 15 years and ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0036PEA,DP02_0036PM,DP02_0036PMA",NaN,"[DP02_0036PEA, DP02_0036PM, DP02_0036PMA]"
1416,DP05_0098PE,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0098PEA,DP05_0098PM,DP05_0098PMA",NaN,"[DP05_0098PEA, DP05_0098PM, DP05_0098PMA]"

In [23]:
df_data_vars = df[~df["variable"].isin(["for", "in", "ucgid"])]
df_data_vars

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required,attributes_list
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN,"[DP02_0126EA, DP02_0126M, DP02_0126MA]"
4,DP05_0050PE,Percent!!RACE!!Total population!!One race!!Bla...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0050PEA,DP05_0050PM,DP05_0050PMA",NaN,"[DP05_0050PEA, DP05_0050PM, DP05_0050PMA]"
5,DP04_0047E,Estimate!!HOUSING TENURE!!Occupied housing uni...,Selected Housing Characteristics,int,DP04,0,NaN,NaN,"DP04_0047EA,DP04_0047M,DP04_0047MA",NaN,"[DP04_0047EA, DP04_0047M, DP04_0047MA]"
6,DP02PR_0083PE,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Selected Social Characteristics in Puerto Rico,float,DP02PR,0,NaN,NaN,"DP02PR_0083PEA,DP02PR_0083PM,DP02PR_0083PMA",NaN,"[DP02PR_0083PEA, DP02PR_0083PM, DP02PR_0083PMA]"
7,DP02PR_0106PE,Percent!!WORLD REGION OF BIRTH OF FOREIGN-BORN...,Selected Social Characteristics in Puerto Rico,float,DP02PR,0,NaN,NaN,"DP02PR_0106PEA,DP02PR_0106PM,DP02PR_0106PMA",NaN,"[DP02PR_0106PEA, DP02PR_0106PM, DP02PR_0106PMA]"
...,...,...,...,...,...,...,...,...,...,...,...
1412,DP03_0039PE,Percent!!INDUSTRY!!Civilian employed populatio...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0039PEA,DP03_0039PM,DP03_0039PMA",NaN,"[DP03_0039PEA, DP03_0039PM, DP03_0039PMA]"
1413,DP02_0098E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0098EA,DP02_0098M,DP02_0098MA",NaN,"[DP02_0098EA, DP02_0098M, DP02_0098MA]"
1414,DP04_0095PE,Percent!!SELECTED MONTHLY OWNER COSTS (SMOC)!!...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0095PEA,DP04_0095PM,DP04_0095PMA",NaN,"[DP04_0095PEA, DP04_0095PM, DP04_0095PMA]"
1415,DP02_0036PE,Percent!!MARITAL STATUS!!Females 15 years and ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0036PEA,DP02_0036PM,DP02_0036PMA",NaN,"[DP02_0036PEA, DP02_0036PM, DP02_0036PMA]"
1416,DP05_0098PE,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0098PEA,DP05_0098PM,DP05_0098PMA",NaN,"[DP05_0098PEA, DP05_0098PM, DP05_0098PMA]"

In [24]:
df_data_vars.sort_values(by = 'variable')

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required,attributes_list
1276,AIANHH,American Indian Area/Alaska Native Area/Hawaii...,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
1178,ANRC,Alaska Native Regional Corporation,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
1004,CBSA,Metropolitan/Micropolitan Statistical Area,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
377,CD,Congressional District,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
881,COUNTY,County,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...
601,SDSEC,School District (Secondary),NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
916,SDUNI,School District (Unified),NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
394,STATE,State,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]
96,SUMLEVEL,Summary Level code,NaN,string,N/A,0,NaN,NaN,NaN,NaN,[]
482,UA,Urban Area,NaN,NaN,N/A,0,NaN,NaN,NaN,NaN,[]

In [ ]:
# Load and prep the metadata

def load_profile_metadata(json_path):
    with open(json_path, "r") as f:
        meta = json.load(f)

    df_meta = (
        pd.DataFrame.from_dict(meta["variables"], orient="index")
          .reset_index()
          .rename(columns={"index": "variable"})
    )

    # Keep only the most useful columns for a "website-like" table
    keep = ["variable", "label", "concept", "group", "predicateType"]
    keep = [c for c in keep if c in df_meta.columns]
    df_meta = df_meta[keep]

    return df_meta

In [ ]:
# Turn the API pull inot "variables in rows, geos in columns"

def profile_to_wide_table(
    df_api,
    df_meta,
    geo_cols=("NAME", "state", "public use microdata area"),
    geo_label_col="NAME",
    include_metadata_cols=("label", "concept", "group"),
    value_cast="numeric",  # "numeric" or "keep"
):
    """
    df_api: DataFrame returned from api_response_to_df()
    df_meta: DataFrame returned from load_profile_metadata()

    geo_cols: columns that identify geography in the API response.
              For PUMAs you often have: state, public use microdata area, NAME.
    geo_label_col: which geo column to display as the column header (often NAME).
    include_metadata_cols: metadata fields to include as left-most columns in output.
    value_cast: cast values to numeric when possible.
    """

    geo_cols = [c for c in geo_cols if c in df_api.columns]

    # Identify which columns are actual variables (exclude geo identifiers)
    var_cols = [c for c in df_api.columns if c not in geo_cols]

    # Create a single geography key/label for the pivot columns
    if geo_label_col in df_api.columns:
        df_api = df_api.copy()
        df_api["geo"] = df_api[geo_label_col].astype(str)
    else:
        # fallback: concatenate geo parts
        df_api = df_api.copy()
        df_api["geo"] = df_api[geo_cols].astype(str).agg(" | ".join, axis=1)

    # Long form: (geo, variable, value)
    df_long = df_api.melt(
        id_vars=["geo"],
        value_vars=var_cols,
        var_name="variable",
        value_name="value"
    )

    # Optionally cast numeric
    if value_cast == "numeric":
        df_long["value"] = pd.to_numeric(df_long["value"], errors="ignore")
        # If you prefer strictly numeric with NaN for non-numeric:
        # df_long["value"] = pd.to_numeric(df_long["value"], errors="coerce")

    # Join metadata
    df_long = df_long.merge(df_meta, on="variable", how="left")

    # Build a row index: variable + chosen metadata columns
    row_cols = ["variable"] + [c for c in include_metadata_cols if c in df_long.columns]

    # Pivot: rows = variables, columns = geos
    wide = (
        df_long.pivot_table(
            index=row_cols,
            columns="geo",
            values="value",
            aggfunc="first"   # each (geo, variable) should be unique
        )
        .reset_index()
    )

    # Optional: sort columns nicely (metadata first, then geos)
    meta_part = row_cols
    geo_part = [c for c in wide.columns if c not in meta_part]
    wide = wide[meta_part + geo_part]

    return wide

In [ ]:
# Export to excel (or csv)
def export_tables(wide_df, out_xlsx="acs_profile_wide.xlsx", out_csv=None):
    # Excel
    with pd.ExcelWriter(out_xlsx, engine="openpyxl") as writer:
        wide_df.to_excel(writer, sheet_name="Profile (wide)", index=False)

    # Optional CSV (note: very wide CSVs can be awkward)
    if out_csv:
        wide_df.to_csv(out_csv, index=False)

In [ ]:
# Example
# 1) df_api from your Census API response
df_api = api_response_to_df(api_response)

# 2) metadata from the variables JSON for this endpoint/vintage
df_meta = load_profile_metadata("ACS1_profile_variables_2024.json")

# 3) build website-like wide layout
wide_df = profile_to_wide_table(
    df_api=df_api,
    df_meta=df_meta,
    geo_cols=("NAME", "state", "public use microdata area"),
    geo_label_col="NAME",
    include_metadata_cols=("label", "concept", "group"),
    value_cast="keep"  # profiles often have many percents/strings; choose what you prefer
)

# 4) export
export_tables(wide_df, out_xlsx="acs1_profile_pumas_2024_wide.xlsx")